version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: git-next
    main: ./cmd/git-next
    binary: git-next
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: git-next
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"

release:
  github:
    owner: VectorSophie
    name: git-next
  draft: false
  prerelease: auto

brews:
  - repository:
      owner: VectorSophie
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/VectorSophie/git-next
    description: "Git advice that doesn't lie"
    license: MIT
    test: |
      system "#{bin}/git-next --version"
    install: |
      bin.install "git-next"

nfpms:
  - id: git-next
    package_name: git-next
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}"
    homepage: https://github.com/VectorSophie/git-next
    description: "Git advice that doesn't lie"
    maintainer: VectorSophie <jay7math.com>
    license: MIT
    vendor: VectorSophie
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin

announce:
  skip: true
